[params]

pot = 213
channel = 0
j = 1
np1 = 25
np2 = 15
p1 = 1.5
p2 = 10.0
p3 = 50
mapp = 'trns'
c = 8.0
# Defining constants
#h_barc = 197.3269804  # Mev fm
#two_mu = 938.918747  # MeV
#E = [10.0, 20.0, 40.0]

# dummy = 20.